KJG-68 Digitale Mitgliedskarte
fabitb/KjG-MuF-App pull request #26
Opened 2024-06-01 14:43 UTC by Olischne

Lädt Accountinformationen mit Scraping (keine Permission für GetMember)

- Mitgliedsnummer (z.B. "2500005833")
- Ebene und übergeordnete Ebene (z.B. "ME Trudering" und "KjG München und Freising")

Digitale Mitgliedskarte (Design angelehnt an Beispiel in KjG style guide)

- Name
- Mitgliedsnummer
- Übergeordnete Ebene
- Ebene
- Rückseite für QR-Code oder ähnliches (für Miles und Morus / vor Ort Anmeldung?)

2024-06-09 10:00 UTC, fabitb requested changes
Sieht wirklich sehr cool aus! Genauso habe ich mir das damals vorgestellt, als wir das Ticket angelegt haben. 
Wir haben aktuell noch das Problem, dass wenn die User das Update machen und noch eingeloggt sind, dann zeigt die Mitgliedskarte nur den Namen und lädt nur alle Daten wenn man sich reloggt.
Also entweder bräuchten wir einen Hinweis auf der Karte, dass man sich reloggt oder wir bauen ein Boolean Flag in die Shared Preferences ein, dass die neuen Infos noch nicht geladen wurden nach update, wir dann alles laden und dann den Boolean umstellen. Dann wird das einmal am Anfang gemacht oder bei initialen Einloggen.
Oder hast du noch andere Ideen?

2024-06-09 10:09 UTC, fabitb commented on lib/main.dart
> +                  IconButton(
Das Icon hat aktuell so nen Standard Grau Farbton. Würde das noch auf Schwarz ändern, wie der Appbar Titel und das Hamburgermenü Icon

2024-06-09 14:28 UTC, Olischne commented on lib/main.dart
> +                  IconButton(
Fun fact: die anderen Sachen sind auch nicht schwarz... Ich verstehe nur nicht warum der Knopf nicht die richtige Farbe aus dem Theme bekommt. Ich seh jetzt gerade aber auch nicht wie ich an die richtige Farbe komme, wenn du Ideen hast gerne mal ausprobieren

2024-06-09 15:12 UTC, Olischne commented on lib/ui/widgets/member_card.dart
Man könnte es sich natürlich deutlich leichter machen, wenn man die Vorder- und Rückseite einfach jeweils als Bild reinmacht, dann müsste man nur den Text positionieren.

2024-06-09 15:17 UTC, Olischne commented on lib/ui/screens/login_screen.dart
> +                                    "Login erfolgreich, lade weitere Nutzerdaten",
Cool, habs für den ganzen Login Screen gleich gemacht wenn ich eh schon dabei bin. Hab auch noch eine Extension gemacht weil es mir zu nervig ist das immer ganz auszuschreiben

2024-06-09 15:33 UTC, Olischne commented
> Sieht wirklich sehr cool aus! Genauso habe ich mir das damals vorgestellt, als wir das Ticket angelegt haben. Wir haben aktuell noch das Problem, dass wenn die User das Update machen und noch eingeloggt sind, dann zeigt die Mitgliedskarte nur den Namen und lädt nur alle Daten wenn man sich reloggt. Also entweder bräuchten wir einen Hinweis auf der Karte, dass man sich reloggt oder wir bauen ein Boolean Flag in die Shared Preferences ein, dass die neuen Infos noch nicht geladen wurden nach update, wir dann alles laden und dann den Boolean umstellen. Dann wird das einmal am Anfang gemacht oder bei initialen Einloggen. Oder hast du noch andere Ideen?

Wir machen ja eh bei jedem App Start einen check, ob der Login noch korrekt ist. Dort hab ich jetzt einfach einen check gemacht ob das schon geladen wurde, sonst lade ich es nachträglich.

2024-06-12 20:06 UTC, fabitb approved these changes

2024-06-12 20:06 UTC, merged